_extends: .github
repository:
  name: eslint-config-react
  description: Shareable config for ESLint for React components
  homepage: 'https://npm.im/@gaincompliance/eslint-config-react'
  private: false
